parameters:
    ali_doctrine_data_loader.class: Ali\DoctrineDataLoaderBundle\Util\Loader

services:
    ali_doctrine_data_loader:
        class: %ali_doctrine_data_loader.class%
        arguments: [@doctrine.orm.entity_manager]
